### ISSUE TITLE
Can't use cache key with no cache?

### ISSUE THREAD

**Issue by joshua-martin** [benjamminf/craft-nocache#4]
Hiya,

Take the following
````
{% cache globally using key 'cache__key' for 1 month %}
   Cache me

    {% nocache %}
      Do not cache me
    {% endnocache %}
  {% endcache %}
````
This caches in `craft_templatecaches` as `cache__key` with a body of `cache me <no-cache>3HkJuIQdEFS4Rvv50KnpVs3s-fIhF5j7S</no-cache>`, which seems correct to me.

However, if I update the 'Do not cache me' text, the nocache block doesn't update. If I do not use a `key` then it updates correctly. 

So this leads me to believe that it is not possible to use `key` parameter with no cache? 

Thanks

**Comment by wjthomas9** [comment]
I'm trying to do the same thing. Is this a bug, or is this outside the capability of this plugin?

**Comment by benjamminf** [comment]
This is an interesting side effect. No cache is still performing as expected (if you output the current time in your no-cache block you'll see it update with each refresh) but the issue is it's not recompiling the template when you make changes. This is only a problem when developing, in which case you probably shouldn't have caching enabled when working in your dev environment. When publishing your template changes, you can clear your compiled templates through the Craft CP.

To clarify, this is actually a Craft CMS "feature", and has little to do with this plugin. Given the following code:

```twig
{% cache using key 'xyz' %} Hello world {% endcache %}
```

changing the contents "Hello world" will show the same behaviour, and will not update after saving the page when it should. I'm not sure if this is intentional or not, but if you disable caching during development (which should be the case if you have `devMode` enabled in your config) then this behaviour shouldn't really affect you.

**Comment by joshua-martin** [comment]
Thanks for the reply. Might be worth putting this as a note in the README, as its not beyond the realms of possibility for one to be testing a site with cache enabled on a local dev server. Quite the 'gotcha' it seems!

**Comment by wjthomas9** [comment]
+1 on adding a little warning to the README about testing on Dev.

**Comment by wjthomas9** [comment]
I'm trying to pass a variable to nocache, and I'm not having any luck. Is this related to the issue you described above? Or am I mis-understanding the variable passing technique?

This works:

    {% cache globally using key 'home_page' %}
        {% nocache %}
            {{ craft.request.getQueryString }}
        {% endnocache %}
    {% endcache %}

This does not work:

    {% set params = craft.request.getQueryString %}

    {% cache globally using key 'home_page' %}
        {% nocache with { paramsVar: params } %}
            {{ paramsVar }}
        {% endnocache %}
    {% endcache %}

**Comment by joshua-martin** [comment]
As per the README caveat, You'll want to use
````
{% cache globally using key 'home_page' %}
    {% set params = craft.request.getQueryString %}

    {% nocache with { paramsVar: params } %}
        {{ paramsVar }}
    {% endnocache %}
{% endcache %}
````

**Comment by wjthomas9** [comment]
That doesn't seem to work either. I get the same output either way. Is that due to the issue described above?

**Comment by joshua-martin** [comment]
````
{% cache globally using key 'home_page' %}
    {% nocache %}
        {% set params = craft.request.getQueryString %}
        {{ params }}
    {% endnocache %}
{% endcache %}
````

Try this? Certainly seems to be temperamental - but I suspect as @benjamminf has said, this is more to with caching from Craft, rather than issues in the plugin.

**Comment by wjthomas9** [comment]
That is pretty much the same as my first example where I just grab the param directly, which does work. In this case, there's no reason to set the variable anymore. After re-reading through the caveat, I think I understand a little better why it doesn't work to pass a variable in that was defined outside of the cache and nocache blocks.

**Comment by benjamminf** [comment]
As long as the variable is outside of the `nocache` block, whether the variable is inside the `cache` block or outside doesn't matter (unless it's a variable that can bust caches, like a Craft element). What happens is that variables passed into `nocache` have themselves been cached, which is why your example doesn't work. They're cached when the surrounding `cache` block is cached. Hard to explain why that's the case, but you might also be wondering what's the point?

I suppose it's main function is to ensure that the caching block actually does it's job and prevents further database calls. In the products example in the readme, that product ID is cached and passed to `nocache`, but it could have also passed the whole product. The great thing is the `nocache` block wouldn't have to re-query for that product.

For getting request parameters, that's something that you'd want to do inside the `nocache` block, since the value of that would actually get cached.

This is tricky to explain and also to understand, but hopefully this sheds some more light on what's going on. When in doubt, don't pass your variables but redeclare them inside the `nocache` block. There's a lot I should mention in the readme, but it's already a novel haha. The compiled templates issue is something I will add though.

**Comment by mcclaskiem** [comment]
I just experienced a similar issue with Commerce and a user's Cart. I ended up having to do:

```
{% nocache %}
    <p class="cart-amount">{{craft.commerce.cart.totalQty}}</p>
{% endnocache %}
```

Originally I had:
```
{% nocache with {cartQty: cart.totalQty} %}
    <p class="cart-amount">{{cartQty}}</p>
{% endnocache %}
```
Where `cart` was set in `_layout.twig`
